name: Teste de Instalação de Pacotes R

on:
  workflow_dispatch: # Permite que seja executado apenas manualmente

jobs:
  test-install:
    name: Testar Instalação
    runs-on: ubuntu-latest
    steps:
      - name: Configurar R e instalar pacotes
        uses: r-lib/actions/setup-r@v2.4.0
        with:
          r-version: '4.4.1'
          r-packages: |
            dplyr
